### ISSUE TITLE
how to fine-tune models with multi-nodes

### ISSUE THREAD

**Issue by panjianfei** [NVIDIA/NeMo-Aligner#185]
if i don't have a slurm cluster，how to fine-tune models based on NeMo-aligner with multi-nodes, can u show a demo?
can i use torchrun to start distributed task with NeMo-Aligner?

**Comment by odelalleau** [comment]
I'm not familiar with non-SLURM setups, but we do the distributed initialization using PyTorch Lightning, so hopefully what works with PTL should work here as well.

**Comment by panjianfei** [comment]
get it, thank you👍👍👍
